openapi: 3.0.0
info:
  version: "1.0.0"
  title: GovPay - API Pendenze
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - url: ${it.govpay.apiurl}/govpay/backend/api/pendenze/rs/v1/
tags:
  - name: Pagamenti
    description: Realizzazione e consultazione dei pagamenti delle pendenze
  - name: Pendenze
    description: Consultazione delle posizioni debitorie
  - name: Utenti
    description: Anagrafica degli Utenti    
security:
  - basicAuth: []    
paths:
  '/pendenze':
    get:
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/get_pendenze'
  '/pendenze/{idA2A}/{idPendenza}':
    put:
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/put_pendenza'
    patch:
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/patch_pendenza'
    get:
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/get_pendenza'
  '/rpp':
    get:  
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpps'
  '/rpp/{idDominio}/{iuv}/{ccp}':
    get:
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp'      
  '/rpp/{idDominio}/{iuv}/{ccp}/rpt':
    get:
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp_rpt'           
  '/rpp/{idDominio}/{iuv}/{ccp}/rt':
    get:
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp_rt'   
  '/profilo':
    get:
      summary: Elenco delle acl associate all'utenza chiamante
      tags:
        - Utenti
      $ref: './utenti.yaml#/get_profilo'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic