# This file contains reusable openapi-v3 entities for defining
#   interoperable API behavior by adopting developers.
#
# You can reference components via JSON-refs https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03
#  eg. $ref: 'https://gigantic-server.com/schemas/Monster/schema.json'
#
openapi: 3.0.0
components:
  parameters:
    # Generic parameters for pagination defined in
    idDominio:
      name: idDominio
      in: query
      description: Identificativo del dominio dell'ente
      required: true
      schema:
        type: string
    iuv:
      name: iuv
      in: query
      description: Identificativo del versamento
      required: true
      schema:
        type: string
    ccp:
      name: ccp
      in: query
      description: Codice contesto pagamento
      required: true
      schema:
        type: string        
    idA2A:
      name: idA2A
      in: query
      description: Identificativo del gestionale ente
      required: true
      schema:
        type: string
    idPendenza:
      name: idPendenza
      in: query
      description: Identificativo della pendenza nel gestionale ente
      required: true
      schema:
        type: string        
    idDebitore:
      name: idDebitore
      in: query
      description: Identificativo del soggetto debitore della pendenza
      required: false
      schema:
        type: string
      example: 'RSSMRA30A01H501I'
    idVersante:
      name: idDebitore
      in: query
      description: Identificativo del soggetto versante del pagamento
      required: false
      schema:
        type: string
      example: 'RSSMRA30A01H501I'      
    idPagamento:
      name: idSessionePortale
      in: query
      description: Identificativo della richiesta di pagamento
      required: false
      schema:
        type: string     
      example: 'c8be909b-2feb-4ffa-8f98-704462abbd1d'         
    idSessionePortale:
      name: idSessionePortale
      in: query
      description: Identificativo della sessione di pagamento assegnato dall'EC
      required: false
      schema:
        type: string     
      example: 'c8be909b-2feb-4ffa-8f98-704462abbd1d'   
    idSessionePsp:
      name: idSessionePsp
      in: query
      description: Identificativo della sessione di pagamento assegnato da pagoPA
      required: false
      schema:
        type: string
      example: 'c8be909b-2feb-4ffa-8f98-704462abbd1d'
    statoPagamento:
      name: statoPagamento
      in: query
      description: Filtro sullo stato del pagamento
      required: false
      schema:
        $ref: 'govpay-commons-v2.yaml#/components/schemas/StatoPagamento'
    statoPendenza:
      name: statoPendenza
      in: query
      description: Filtro sullo stato del pendenza
      required: false
      schema:
        $ref: 'govpay-commons-v2.yaml#/components/schemas/StatoPendenza'
    esitoPagamento:
      name: statoPendenza
      in: query
      description: Filtro sullo stato del pendenza
      required: false
      schema:
        $ref: 'govpay-commons-v2.yaml#/components/schemas/EsitoRpp'        
        
        
        
                 