# This file contains reusable openapi-v3 entities for defining
#   interoperable API behavior by adopting developers.
#
# You can reference components via JSON-refs https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03
#  eg. $ref: 'https://gigantic-server.com/schemas/Monster/schema.json'
#
openapi: 3.0.0
components:
  schemas:
    Pagamenti:
      type: object
      allOf:
        - $ref: 'components-lg-v3.yaml#/components/schemas/Lista' 
        - type: object
          properties:
            items:
              type: array
              items: 
                $ref: '#/components/schemas/PagamentoIndex'  
    Pagamento:
      type: object
      allOf:
        - $ref: '#/components/schemas/PagamentoBase'  
        - type: object
          required:
            - pendenze
          properties:
            pendenze:
              $ref: 'govpay-pendenza-v2.yaml#/components/schemas/Pendenze'
            rpp:
              $ref: 'govpay-rpp-v2.yaml#/components/schemas/Rpps'  
    PagamentoIndex:
      type: object
      allOf:
        - $ref: '#/components/schemas/PagamentoBase'  
        - type: object
          required:
            - href
            - pendenze
          properties:
            href:
              type: string
              description: URL del pagamento
            pendenze:
              type: string
              description: URL della lista delle pendenze oggetto del pagamento
            rpp:
              type: string
              description: URL della lista delle richieste di pagamento attivate  
    PagamentoBase:
      type: object
      allOf:
        - $ref: '#/components/schemas/NuovoPagamentoBase'  
        - type: object
          required:
            - id
            - nome
            - stato
            - importo
          properties:
            id:
              type: string
              example: 'f9866575-e255-4d10-9845-57ba88bec136'
              description: Identificativo del pagamento assegnato da GovPay
            nome:
              type: string
              example: 'Immatricolazione AA 2017/2018 ed altre 3 pendenze'
              description: Identificativo del pagamento assegnato da GovPay
            stato:
              $ref: 'govpay-commons-v2.yaml#/components/schemas/StatoPagamento'
            importo:
              type: number
              description: >-
                Importo del pagamento. Corrisponde alla somma degli importi delle pendenze al momento della richiesta
            idSessionePsp:
              type: string
              example: '7f905970-cfe9-4ee5-a9a7-81fe14e7437e'
              description: Identificativo del pagamento assegnato dal psp utilizzato
            pspRedirectUrl:
              type: string
              example: 'https://www.psp.it/payment?sessionId=7f905970-cfe9-4ee5-a9a7-81fe14e7437e'
              description: Url di redirect al psp inviata al versante per perfezionare il pagamento, se previsto dal modello                
    NuovoPagamento:   
      type: object
      allOf:
        - $ref: '#/components/schemas/NuovoPagamentoBase'  
        - type: object
          required:
            - pendenze
          properties:
            pendenze:
              type: array
              description: pendenze o riferimenti alle pendenze oggetto del pagamento
              items:
                anyOf:
                  - $ref: 'govpay-pendenza-v2.yaml#/components/schemas/RiferimentoPendenza'
                  - $ref: 'govpay-pendenza-v2.yaml#/components/schemas/RiferimentoAvviso'
                  - $ref: 'govpay-pendenza-v2.yaml#/components/schemas/NuovaPendenza'
    NuovoPagamentoBase:  
      type: object
      properties:
        urlRitorno:
          type: string
          description: >-
            url di ritorno al portale al termine della sessione di pagamento
          example: >-
            https://www.comune.it/pagamentopagopa/abcd-efgh-ijklm-12345
        contoAddebito:
          $ref: 'govpay-commons-v2.yaml#/components/schemas/Conto'
        dataEsecuzionePagamento:
          type: string
          format: date
          example: '2018-12-31'
          description: >-
            data in cui si richiede che venga effettuato il pagamento, se diversa dalla data corrente.
        credenzialiPagatore:
          type: string
          description: >-
            Eventuali credenziali richieste dal PSP necessarie per
            completare l'operazione (ad esempio un codice bilaterale
            utilizzabile una sola volta).
        soggettoVersante:
          $ref: 'govpay-commons-v2.yaml#/components/schemas/Soggetto'
        autenticazioneSoggetto:
          $ref: 'govpay-commons-v2.yaml#/components/schemas/TipoAutenticazioneSoggetto'