openapi: 3.0.0
components:
  schemas:
    Rpps:
      type: object
      allOf:
        - $ref: 'components-lg-v3.yaml#/components/schemas/List' 
        - type: object
          properties:
            items:
              type: array
              items: 
                $ref: '#/components/schemas/RppIndex'      
    RppIndex:
      type: object
      allOf:
        - $ref: '#/components/schemas/RppBase'
        - type: object
          required:
            - href
            - pendenza
          properties:
            href:
              type: string
              description: URL della rpp
            pendenza:
              type: string
              description: Url alla pendenza oggetto della richiesta di pagamento          
    Rpp:
      type: object
      allOf:
        - $ref: '#/components/schemas/RppBase'
        - type: object
          required:
            - pendenza
          properties:
            pendenza:
              $ref: 'govpay-pendenza-v2.yaml#/components/schemas/PendenzaIndex'         
    RppBase:
      type: object
      required: 
        - stato
        - rpt
      properties:
        stato:
          type: string
          description: Stato della richiesta di pagamento sulla piattaforma PagoPA.
          example: RT_ACCETTATA_PA
        dettaglioStato:
          type: string
          description: >-
            Dettaglio fornito dal Nodo dei Pagamenti sullo stato della
            richiesta.
        segnalazioni:
          type: array
          items: 
            $ref: 'govpay-commons-v2.yaml#/components/schemas/Segnalazione'
        rpt:
          type: object
          description: "Rpt inviata a PagoPa. {http://www.digitpa.gov.it/schemas/2011/Pagamenti/} ctRichiestaPagamentoTelematico"
        rt:
          type: object
          description: "Rt inviata da PagoPa. {http://www.digitpa.gov.it/schemas/2011/Pagamenti/} ctRicevutaTelematica"  
    