openapi: 3.0.0
info:
  version: "1.0.0"
  title: GovPay - API Pagamento
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - url: ${it.govpay.apiurl}/govpay/frontend/api/pagamento/rs/v1/
tags:
  - name: Pagamenti
    description: Realizzazione e consultazione dei pagamenti delle pendenze
  - name: Pendenze
    description: Consultazione delle posizioni debitorie
  - name: Domini
    description: Anagrafica degli Enti Creditori    
  - name: Utenti
    description: Anagrafica degli Utenti
security:
  - basicAuth: []    
paths:
  '/domini':
    get:
      summary: Elenco degli Enti Creditori
      tags:
        - Domini
      $ref: './domini.yaml#/get_domini'
  '/domini/{idDominio}':
    get:
      summary: Lettura dell'anagrafica di un Ente Creditore
      tags:
        - Domini
      $ref: './domini.yaml#/get_dominio'
  '/domini/{idDominio}/unitaOperative':
    get:
      summary: Elenco delle Unità Operative di un Ente Creditore
      tags:
        - Domini
      $ref: './domini.yaml#/get_unitaoperative'
  '/domini/{idDominio}/unitaOperative/{idUnitaOperativa}':
    get:
      summary: Lettura dell'anagrafica di una Unità Operativa
      tags:
        - Domini
      $ref: './domini.yaml#/get_unitaoperativa'
  '/domini/{idDominio}/contiAccredito':
    get:
      description: Elenco dei conti di accredito di un Ente Creditore
      tags:
        - Domini
      $ref: './domini.yaml#/get_ibans'
  '/domini/{idDominio}/contiAccredito/{iban}':
    get:
      summary: Lettura dei dati di dettaglio di un conto di accredito
      tags:
        - Domini
      $ref: './domini.yaml#/get_iban'
  '/domini/{idDominio}/entrate':
    get:
      summary: Elenco delle entrate di un Ente Creditore
      tags:
        - Domini
      $ref: './domini.yaml#/get_entrate'
  '/domini/{idDominio}/entrate/{idEntrata}':
    get:
      summary: Lettura dei dati di confiugrazione di una entrata
      tags:
        - Domini
      $ref: './domini.yaml#/get_entrata'
  '/pagamenti':
    post:
      summary: Avvio di un pagamento di un carrello di pendenze
      tags:
        - Pagamenti
      $ref: './pagamenti.yaml#/post_pagamento'
    get:
      summary: Elenco dei pagamenti
      tags:
        - Pagamenti
      $ref: './pagamenti.yaml#/get_pagamenti'
  '/pagamenti/{id}':
    get:
      summary: Lettura dei dati di un pagamento
      tags:
        - Pagamenti    
      $ref: './pagamenti.yaml#/get_pagamento'
  '/pendenze':
    get:
      summary: Elenco delle pendenze
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/get_pendenze'
  '/pendenze/{idA2A}/{idPendenza}':
    get:
      summary: Lettura dei dati di una pendenza
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/get_pendenza'
  '/rpp':
    get:  
      summary: Elenco delle richieste di pagamento pendenza
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpps'
  '/rpp/{idDominio}/{iuv}/{ccp}':
    get:
      summary: Lettura dei dati di una richiesta di pagamento pendenza
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp'      
  '/rpp/{idDominio}/{iuv}/{ccp}/rpt':
    get:
      summary: Acquisizione di una Richiesta di Pagamento Telematica
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp_rpt'           
  '/rpp/{idDominio}/{iuv}/{ccp}/rt':
    get:
      summary: Acquisizione di una Ricevuta Telematica
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp_rt'              
  '/avvisi/{idDominio}/{iuv}':
    get:
      summary: Lettura dei dati di un avviso di pagamento
      tags:
        - Pendenze
      $ref: './avvisi.yaml#/get_avviso'
  '/profilo':
    get:
      summary: Elenco delle acl associate all'utenza chiamante
      tags:
        - Utenti
      $ref: './utenti.yaml#/get_profilo'      
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
