openapi: 3.0.0
info:
  version: "1.0.0"
  title: GovPay - API Pagamento
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - description: SwaggerHub API Auto Mocking
    url: ${api-base-url}
tags:
  - name: Pagamenti
    description: Realizzazione e consultazione dei pagamenti delle pendenze
  - name: Pendenze
    description: Consultazione delle posizioni debitorie
  - name: Domini
    description: Anagrafica degli Enti Creditori    
security:
  - basicAuth: []    
paths:
  '/domini':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_domini'
  '/domini/{idDominio}':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_dominio'
  '/domini/{idDominio}/unitaOperative':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_unitaoperative'
  '/domini/{idDominio}/unitaOperative/{idUnitaOperativa}':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_unitaoperativa'
  '/domini/{idDominio}/ibanAccredito':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_ibans'
  '/domini/{idDominio}/ibanAccredito/{ibanAccredito}':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_iban'
  '/domini/{idDominio}/entrate':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_entrate'
  '/domini/{idDominio}/entrate/{idEntrata}':
    get:
      tags:
        - Domini
      $ref: './domini.yaml#/get_entrata'
  '/pagamenti':
    post:
      tags:
        - Pagamenti
      $ref: './pagamenti.yaml#/post_pagamento'
    get:
      tags:
        - Pagamenti
      $ref: './pagamenti.yaml#/get_pagamenti'
  '/pagamenti/{id}':
    get:
      tags:
        - Pagamenti    
      $ref: './pagamenti.yaml#/get_pagamento'
  '/pendenze':
    get:
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/get_pendenze'
  '/pendenze/{idA2A}/{idPendenza}':
    get:
      tags:
        - Pendenze
      $ref: './pendenze.yaml#/get_pendenza'
  '/rpp':
    get:  
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpps'
  '/rpp/{idDominio}/{iuv}/{ccp}':
    get:
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp'      
  '/rpp/{idDominio}/{iuv}/{ccp}/rpt':
    get:
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp_rpt'           
  '/rpp/{idDominio}/{iuv}/{ccp}/rt':
    get:
      tags:
        - Pagamenti
      $ref: './rpp.yaml#/get_rpp_rt'              
  '/avvisi/{idDominio}/{iuv}':
    get:
      tags:
        - Pendenze
      $ref: './avvisi.yaml#/get_avviso'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic